<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Bronzeman</RootNamespace>
    <AssemblyName>Bronzeman</AssemblyName>
    <Version>2.0.0</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="gunsmith.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
